const state={
 balance:Number(localStorage.getItem('krish_balance')||128.50),
 claimed:localStorage.getItem('krish_claimed')==='1',
 user:JSON.parse(localStorage.getItem('krish_user')||'null'),
 activities:JSON.parse(localStorage.getItem('krish_activities')||'[]')
};
const $=id=>document.getElementById(id);
function money(n){return '₹'+Number(n).toFixed(2)}
function save(){localStorage.setItem('krish_balance',state.balance.toFixed(2));localStorage.setItem('krish_claimed',state.claimed?'1':'0');localStorage.setItem('krish_user',JSON.stringify(state.user));localStorage.setItem('krish_activities',JSON.stringify(state.activities));}
function showToast(msg){const t=$('toast');t.textContent=msg;t.classList.add('show');clearTimeout(window.toastTimer);window.toastTimer=setTimeout(()=>t.classList.remove('show'),2200)}
function update(){ $('balance').textContent=money(state.balance); renderActivity(); }
function addActivity(label,amount,icon='✨'){state.activities.unshift({label,amount,time:'Just now',icon});state.activities=state.activities.slice(0,8);save();update()}
function earn(amount,label,icon='💰'){state.balance+=amount;addActivity(label,amount,icon);showToast(label+' • '+money(amount)+' added');}
function claimDaily(){if(state.claimed){showToast('Daily reward already claimed');return}state.claimed=true;earn(5,'Daily Reward','🎁')}
function runTask(label,amount){earn(amount,label,'⚡')}
function renderActivity(){const el=$('activityList');if(!el)return;const rows=state.activities.length?state.activities: [{label:'Welcome to Krish Earn',amount:0,time:'Ready to start',icon:'🌱'}];el.innerHTML=rows.map(x=>`<div class="activity-row"><span class="act-icon">${x.icon||'✨'}</span><div><b>${x.label}</b><small>${x.time}</small></div><strong>${x.amount>0?'+'+money(x.amount):'—'}</strong></div>`).join('')}
function go(page){document.querySelectorAll('.bottom-nav button').forEach(b=>b.classList.toggle('active',b.dataset.page===page));if(page==='home'){closeModal();window.scrollTo({top:0,behavior:'smooth'});return} if(page==='earn')openEarn();if(page==='tasks')openTasks();if(page==='refer')openRefer();if(page==='wallet')openWallet();if(page==='withdraw')openWithdraw();if(page==='profile')openProfile()}
function openModal(title,html){$('modalContent').innerHTML=`<h2>${title}</h2>${html}`;$('modal').classList.add('show')}
function closeModal(){$('modal').classList.remove('show')}
function openEarn(){openModal('💰 Earn & Rewards',`<p>Choose an available option below. Demo rewards are stored on this device.</p><div class="modal-grid"><button class="modal-action" onclick="claimDaily()"><b>🎁 Daily Reward</b><small>Claim +₹5</small></button><button class="modal-action" onclick="runTask('Watch & Learn',10)"><b>▶️ Watch & Learn</b><small>Earn +₹10</small></button><button class="modal-action" onclick="runTask('Quick Survey',15)"><b>📝 Quick Survey</b><small>Earn +₹15</small></button><button class="modal-action" onclick="runTask('Special Task',20)"><b>⚡ Special Task</b><small>Earn +₹20</small></button></div><button class="lime-btn wide" onclick="closeModal();showToast('More earning options coming soon')">Explore more</button>`)}
function openTasks(){openModal('📋 Tasks',`<p>Complete a task and your demo wallet updates instantly.</p><div class="modal-grid"><button class="modal-action" onclick="runTask('Easy Task',5)"><b>🟢 Easy Task</b><small>+₹5 reward</small></button><button class="modal-action" onclick="runTask('Quick Task',10)"><b>🔵 Quick Task</b><small>+₹10 reward</small></button><button class="modal-action" onclick="runTask('Premium Task',20)"><b>🟣 Premium Task</b><small>+₹20 reward</small></button><button class="modal-action" onclick="showToast('No new tasks right now')"><b>🔎 Find Tasks</b><small>Check availability</small></button></div>`)}
function openRefer(){openModal('👥 Refer & Earn',`<p>Share your referral code with friends. Referral rewards can be tracked here.</p><div class="profile-head"><div class="avatar">KR</div><div><b>Your referral code</b><div style="color:var(--lime);font-weight:900;font-size:18px;margin-top:3px">KRISH128</div></div></div><button class="lime-btn wide" onclick="shareRefer()">📤 Share Referral</button><div class="modal-grid"><div class="modal-action"><b>2</b><small>Pending referrals</small></div><div class="modal-action"><b>₹10</b><small>Example reward</small></div></div>`)}
function shareRefer(){const text='Join Krish Earn — Smart Rewards & Earning Platform. My referral code: KRISH128';if(navigator.share)navigator.share({title:'Krish Earn',text}).catch(()=>{});else if(navigator.clipboard)navigator.clipboard.writeText(text).then(()=>showToast('Referral message copied'));else showToast('Referral code: KRISH128')}
function openWallet(){openModal('👛 My Wallet',`<div class="profile-head"><div class="avatar">₹</div><div><small style="color:var(--muted)">Available balance</small><div style="font-size:28px;font-weight:900">${money(state.balance)}</div></div></div><div class="modal-grid"><div class="modal-action"><b>${money(state.balance)}</b><small>Available</small></div><div class="modal-action"><b>₹25.00</b><small>Pending</small></div></div><button class="lime-btn wide" onclick="go('withdraw')">🏦 Withdraw money</button>`)}
function openWithdraw(){openModal('🏦 Withdraw',`<p>Enter your details to create a withdrawal request. Minimum withdrawal: ₹100.</p><label class="form-label">Amount</label><input id="withdrawAmount" class="field" type="number" min="100" value="100"><label class="form-label">Payment method</label><select id="withdrawMethod" class="field"><option>Bank Account</option><option>UPI</option><option>Wallet</option></select><button class="lime-btn wide" onclick="submitWithdrawal()">Submit Withdrawal Request</button>`)}
function submitWithdrawal(){const n=Number($('withdrawAmount').value);if(n<100){showToast('Minimum withdrawal is ₹100');return}if(n>state.balance){showToast('Insufficient balance');return}state.balance-=n;addActivity('Withdrawal request',-n,'🏦');showToast('Withdrawal request submitted');closeModal()}
function openProfile(){const u=state.user;openModal('👤 Profile & Login',u?`<div class="profile-head"><div class="avatar">${(u.name||'K').slice(0,1).toUpperCase()}</div><div><b>${esc(u.name)}</b><small style="display:block;color:var(--muted);margin-top:3px">${esc(u.phone||'Mobile not added')}</small></div></div><div class="modal-grid"><button class="modal-action" onclick="showToast('Profile is saved on this device')"><b>✓ Logged in</b><small>Account status</small></button><button class="modal-action" onclick="logout()"><b>↪ Logout</b><small>Clear local profile</small></button></div><button class="lime-btn wide" onclick="showToast('KYC section opened')">🪪 Manage KYC</button>`:`<p>Login is stored only on this device for this demo interface.</p><label class="form-label">Name</label><input id="loginName" class="field" placeholder="Your name"><label class="form-label">Mobile</label><input id="loginPhone" class="field" inputmode="numeric" placeholder="10-digit mobile number"><button class="lime-btn wide" onclick="loginUser()">🔐 Login / Create Profile</button>`)}
function loginUser(){const name=$('loginName').value.trim();const phone=$('loginPhone').value.trim();if(!name){showToast('Please enter your name');return}state.user={name,phone};save();showToast('Profile saved successfully');openProfile()}
function logout(){state.user=null;save();showToast('Logged out');openProfile()}
function openNotifications(){openModal('🔔 Notifications',`<div class="activity"><div class="activity-row"><span class="act-icon">🎁</span><div><b>Daily rewards</b><small>Claim your daily bonus</small></div><strong>NEW</strong></div><div class="activity-row"><span class="act-icon">✨</span><div><b>Welcome</b><small>Explore Earn, Tasks, Refer and Wallet</small></div><strong>✓</strong></div></div>`)}
function openMenu(){openModal('☰ Krish Earn Menu',`<div class="modal-grid"><button class="modal-action" onclick="go('profile')"><b>👤 Profile / Login</b><small>Account settings</small></button><button class="modal-action" onclick="openAbout()"><b>ℹ️ About</b><small>About Krish Earn</small></button><button class="modal-action" onclick="showToast('Language options coming soon')"><b>🌐 Language</b><small>Choose language</small></button><button class="modal-action" onclick="shareApp()"><b>📤 Share App</b><small>Share Krish Earn</small></button><button class="modal-action" onclick="showToast('Support: use the app contact details')"><b>💬 Support</b><small>Help & support</small></button><button class="modal-action" onclick="showToast('Theme is already optimized for mobile')"><b>🎨 Theme</b><small>Modern dark mode</small></button></div>`)}
function openAllFeatures(){openModal('✨ All Features',`<p>All major app features are available from this menu.</p><div class="modal-grid"><button class="modal-action" onclick="go('earn')"><b>💰 Earn</b><small>Rewards & offers</small></button><button class="modal-action" onclick="go('tasks')"><b>📋 Tasks</b><small>Complete tasks</small></button><button class="modal-action" onclick="go('refer')"><b>👥 Refer</b><small>Invite friends</small></button><button class="modal-action" onclick="go('wallet')"><b>👛 Wallet</b><small>Balance & history</small></button><button class="modal-action" onclick="go('withdraw')"><b>🏦 Withdraw</b><small>Withdrawal request</small></button><button class="modal-action" onclick="go('profile')"><b>👤 Profile</b><small>Login & account</small></button></div>`)}
function openAbout(){openModal('🌱 About Krish Earn',`<p><b>Krish Earn</b> is a colorful mobile-first rewards interface designed for simple navigation.</p><div class="modal-grid"><div class="modal-action"><b>🎁 Daily Rewards</b><small>Simple check-in</small></div><div class="modal-action"><b>📋 Tasks</b><small>Earn through tasks</small></div><div class="modal-action"><b>👥 Refer & Earn</b><small>Referral tools</small></div><div class="modal-action"><b>🏦 Withdraw</b><small>Request payout</small></div></div><p style="margin-top:15px">Developed by <b>Krish Lohar</b>.</p>`)}
function shareApp(){const text='Krish Earn — Smart Rewards & Earning Platform';if(navigator.share)navigator.share({title:'Krish Earn',text,url:location.href}).catch(()=>{});else if(navigator.clipboard)navigator.clipboard.writeText(location.href).then(()=>showToast('App link copied'));else showToast('Share the current app link')}
function esc(s){return String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
window.addEventListener('load',()=>{update();if('serviceWorker' in navigator)navigator.serviceWorker.register('sw.js?v=20261005').catch(()=>{})});
